version: "3.3"

services:
  db:
    container_name: container-db
    image: compose-example:db
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    build:
      context: ./postgres
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5433:5433"
    networks:
      - internal-network

  redis:
    container_name: tcc-redis
    image: compose-example:redis
    build:
      context: ./redis
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - internal-network

  quarkus:
    container_name: container-quarkus
    image: compose-example:quarkus
    build:
      context: ./quarkus
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    networks:
      - internal-network

  node:
    container_name: container-node
    image: compose-example:node
    build:
      context: ./node
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - internal-network

  react:
    container_name: container-react
    image: compose-example:react
    build:
      context: ./react
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge
