version: "3.3"

services:
  node:
    container_name: container-node
    image: pescador95/compose-example:node
    build:
      context: ./node
      dockerfile: Dockerfile
    env_file:
      - ./node.env
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge
