version: "3.3"

services:
  db:
    container_name: container-db
    image: pescador95/compose-example:db
    build:
      context: ./postgres
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5433:5433"
    networks:
      - internal-network

  redis:
    container_name: container-redis
    image: pescador95/compose-example:redis
    build:
      context: ./redis
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - internal-network

  quarkus:
    container_name: container-quarkus
    image: pescador95/compose-example:quarkus
    build:
      context: ./quarkus
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "6000:6000"
    depends_on:
      - db
      - redis
    networks:
      - internal-network

  node:
    container_name: container-node
    image: pescador95/compose-example:node
    build:
      context: ./node
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - internal-network

  react:
    container_name: container-react
    image: pescador95/compose-example:react
    build:
      context: ./react
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge
