name: Building tests and deploy at Cloud Server

on:
  push:
    branches:
      - main

jobs:

  db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Postgres Database Container
        run: docker-compose -f docker-compose.yml build db

  redis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Postgres Database Container
        run: docker-compose -f docker-compose.yml build redis

  quarkus-x86_64:
    runs-on: ubuntu-latest

    env:
      JDK: "amazoncorretto:20.0.2"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Quarkus Backend Container amd64
        run: docker-compose -f docker-compose.yml build quarkus
        env:
          JDK: ${{ env.JDK }}

  quarkus-aarch64:
    runs-on: ubuntu-latest

    env:
      JDK_ARM64: "arm64v8/openjdk:17-jdk-slim"
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Quarkus Backend Container arm64
        run: docker-compose -f docker-compose.yml build quarkus
        env:
          JDK: ${{ env.JDK_ARM64}}

  node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build API Node Container
        run: docker-compose -f docker-compose.yml build node

  react:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build React Container
        run: docker-compose -f docker-compose.yml build react

  deploy:
    needs: [db, quarkus-x86_64, quarkus-aarch64, node, react, redis]
    runs-on: ubuntu-latest

    if: ${{ false }} # Remova essa linha para habilitar o deploy

    env:
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_SERVER: ${{ secrets.SSH_SERVER }}
      SSH_SERVER_KEY: ${{ secrets.SSH_SERVER_KEY }}
      REPOSITORY_PATH: ${{ secrets.REPOSITORY_PATH }}

    steps:
      - name: Add SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan $SSH_SERVER >> ~/.ssh/known_hosts

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_SERVER_KEY }}

      - name: Checkout Main and Pull
        run: |
              ssh $SSH_USERNAME@$SSH_SERVER "sudo su -c 'cd ~/${REPOSITORY_PATH} && git checkout main && git pull'"

      - name: Connect to Oracle Server and Run Commands to Deploy
        run: |
              ssh $SSH_USERNAME@$SSH_SERVER "sudo su -c 'cd ~/${REPOSITORY_PATH} && chmod +x ~/${REPOSITORY_PATH}/run.sh && ./run.sh'"

      - name: Reset run.sh changes
        run: |
              ssh $SSH_USERNAME@$SSH_SERVER "sudo su -c 'cd ~/${REPOSITORY_PATH} && git checkout -- run.sh'"